
management:
  endpoint:
    web:
      exposure:
        include: health

---
spring:
  config:
    activate:
      on-profile: env1
management:
  endpoint:
    web:
      exposure:
        include: health
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: env2

management:
  endpoint:
    web:
      exposure:
        include: health
server:
  port: 8082